// <auto-generated />
using System;
using Marketplace_LabWebBD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Marketplace_LabWebBD.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260105191953_AddNewFieldsToFiltroFavorito")]
    partial class AddNewFieldsToFiltroFavorito
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Admin", b =>
                {
                    b.Property<int>("ID_Utilizador")
                        .HasColumnType("int");

                    b.HasKey("ID_Utilizador")
                        .HasName("PK__Admin__020698172C794F51");

                    b.ToTable("Admin", (string)null);
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Anuncio", b =>
                {
                    b.Property<int>("ID_Anuncio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Anuncio"));

                    b.Property<DateTime?>("Data_Atualizacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Data_Publicacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Estado_Anuncio")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Ativo");

                    b.Property<int>("ID_Carro")
                        .HasColumnType("int");

                    b.Property<int>("ID_Vendedor")
                        .HasColumnType("int");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("Prazo_Reserva_Dias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(7);

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateOnly?>("Reservado_Ate")
                        .HasColumnType("date");

                    b.Property<int?>("Reservado_Por")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("ID_Anuncio")
                        .HasName("PK__Anuncio__D8875FB6F59A892A");

                    b.HasIndex("ID_Carro");

                    b.HasIndex("ID_Vendedor");

                    b.HasIndex("Reservado_Por");

                    b.HasIndex(new[] { "Data_Publicacao" }, "IDX_Anuncio_Data")
                        .IsDescending();

                    b.HasIndex(new[] { "Estado_Anuncio" }, "IDX_Anuncio_Estado");

                    b.HasIndex(new[] { "Preco" }, "IDX_Anuncio_Preco");

                    b.ToTable("Anuncio", (string)null);
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool?>("Bloqueado")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("Data_Aprovacao_Vendedor")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("Data_Bloqueio")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Data_Registo")
                        .HasColumnType("date");

                    b.Property<DateTime?>("Data_Token")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool?>("Email_Validado")
                        .HasColumnType("bit");

                    b.Property<int?>("ID_Admin_Bloqueio")
                        .HasColumnType("int");

                    b.Property<int?>("ID_Aprovacao_Vendedor")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Morada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motivo_Bloqueio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motivo_Rejeicao_Vendedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RolePendente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token_Validacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("VendorApprovalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Carro", b =>
                {
                    b.Property<int>("ID_Carro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Carro"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<string>("Caixa")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Categoria")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Cor")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ID_Combustivel")
                        .HasColumnType("int");

                    b.Property<int>("ID_Modelo")
                        .HasColumnType("int");

                    b.Property<int>("ID_Vendedor")
                        .HasColumnType("int");

                    b.Property<int?>("Lotacao")
                        .HasColumnType("int");

                    b.Property<int>("Quilometragem")
                        .HasColumnType("int");

                    b.HasKey("ID_Carro")
                        .HasName("PK__Carro__8D68D2DEF25E62E4");

                    b.HasIndex("ID_Combustivel");

                    b.HasIndex("ID_Modelo");

                    b.HasIndex("ID_Vendedor");

                    b.HasIndex(new[] { "Ano" }, "IDX_Carro_Ano");

                    b.ToTable("Carro", (string)null);
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Combustivel", b =>
                {
                    b.Property<int>("ID_Combustivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Combustivel"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID_Combustivel")
                        .HasName("PK__Combusti__F8AAF41E8A93ED39");

                    b.HasIndex(new[] { "Tipo" }, "UQ__Combusti__8E762CB418F0EE7E")
                        .IsUnique();

                    b.ToTable("Combustivel", (string)null);
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Compra", b =>
                {
                    b.Property<int>("ID_Compra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Compra"));

                    b.Property<DateOnly>("Data")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Estado_Pagamento")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pendente");

                    b.Property<int>("ID_Anuncio")
                        .HasColumnType("int");

                    b.Property<int>("ID_Comprador")
                        .HasColumnType("int");

                    b.Property<string>("Metodo_Pagamento")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("ID_Compra")
                        .HasName("PK__Compra__A9D5994E525465B7");

                    b.HasIndex("ID_Anuncio");

                    b.HasIndex("ID_Comprador");

                    b.HasIndex(new[] { "Data" }, "IDX_Compra_Data");

                    b.ToTable("Compra", (string)null);
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Comprador", b =>
                {
                    b.Property<int>("ID_Comprador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Comprador"));

                    b.Property<int>("ID_Utilizador")
                        .HasColumnType("int");

                    b.Property<bool?>("Notificacoes_Email")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("Notificacoes_Push")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("ID_Comprador")
                        .HasName("PK__Comprado__5E8ABD9D25E4FB23");

                    b.HasIndex("ID_Utilizador");

                    b.ToTable("Comprador", (string)null);
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Configuracao_Sistema", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descricao_Sobre")
                        .HasColumnType("text");

                    b.Property<string>("Email_Contacto")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Horario_Suporte")
                        .HasColumnType("text");

                    b.Property<string>("Nome_Marketplace")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Politica_Privacidade")
                        .HasColumnType("text");

                    b.Property<string>("Telefone_Contacto")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Termos_Uso")
                        .HasColumnType("text");

                    b.HasKey("ID")
                        .HasName("PK__Configur__3214EC2779958503");

                    b.ToTable("Configuracao_Sistema", (string)null);
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Cria", b =>
                {
                    b.Property<int>("ID_Admin")
                        .HasColumnType("int");

                    b.Property<int>("ID_Utilizador")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Data")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ID_Admin", "ID_Utilizador")
                        .HasName("PK__Cria__09D50EE74F4EDA6F");

                    b.HasIndex("ID_Utilizador");

                    b.ToTable("Cria");
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Filtro_Favorito", b =>
                {
                    b.Property<int>("ID_Filtro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Filtro"));

                    b.Property<int?>("Ano_Max")
                        .HasColumnType("int");

                    b.Property<int?>("Ano_Min")
                        .HasColumnType("int");

                    b.Property<string>("Caixa")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Categoria")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("Data_Criacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("ID_Combustivel")
                        .HasColumnType("int");

                    b.Property<int>("ID_Comprador")
                        .HasColumnType("int");

                    b.Property<int?>("ID_Marca")
                        .HasColumnType("int");

                    b.Property<int?>("ID_Modelo")
                        .HasColumnType("int");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nome_Filtro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Preco_Max")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Preco_Min")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("Quilometragem_Max")
                        .HasColumnType("int");

                    b.HasKey("ID_Filtro")
                        .HasName("PK__Filtro_F__931D1A29C629E33F");

                    b.HasIndex("ID_Combustivel");

                    b.HasIndex("ID_Comprador");

                    b.HasIndex("ID_Marca");

                    b.HasIndex("ID_Modelo");

                    b.ToTable("Filtro_Favorito", (string)null);
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Foto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Fotografia")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("ID_Carro")
                        .HasColumnType("int");

                    b.Property<int?>("Ordem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("ID")
                        .HasName("PK__Foto__3214EC277AC42C3E");

                    b.HasIndex("ID_Carro");

                    b.ToTable("Foto", (string)null);
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Historico_Reserva", b =>
                {
                    b.Property<int>("ID_Historico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Historico"));

                    b.Property<DateOnly?>("Data_Fim")
                        .HasColumnType("date");

                    b.Property<DateTime>("Data_Inicio")
                        .HasColumnType("datetime");

                    b.Property<string>("Estado")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("ID_Anuncio")
                        .HasColumnType("int");

                    b.Property<int>("ID_Comprador")
                        .HasColumnType("int");

                    b.HasKey("ID_Historico")
                        .HasName("PK__Historic__ECA88795102F448E");

                    b.HasIndex("ID_Anuncio");

                    b.HasIndex("ID_Comprador");

                    b.ToTable("Historico_Reserva", (string)null);
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Log_Admin", b =>
                {
                    b.Property<int>("ID_Log")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Log"));

                    b.Property<DateTime>("Data_Hora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<int>("ID_Admin")
                        .HasColumnType("int");

                    b.Property<int?>("ID_Anuncio_Afetado")
                        .HasColumnType("int");

                    b.Property<int?>("ID_Utilizador_Afetado")
                        .HasColumnType("int");

                    b.Property<string>("IP_Address")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Tipo_Acao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID_Log")
                        .HasName("PK__Log_Admi__2DBF3395F154EE25");

                    b.HasIndex("ID_Admin");

                    b.HasIndex("ID_Anuncio_Afetado");

                    b.HasIndex("ID_Utilizador_Afetado");

                    b.ToTable("Log_Admin", (string)null);
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Marca", b =>
                {
                    b.Property<int>("ID_Marca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Marca"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID_Marca")
                        .HasName("PK__Marca__9B8F8DB2BDA72356");

                    b.HasIndex(new[] { "Nome" }, "UQ__Marca__7D8FE3B2485BF692")
                        .IsUnique();

                    b.ToTable("Marca", (string)null);
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Modelo", b =>
                {
                    b.Property<int>("ID_Modelo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Modelo"));

                    b.Property<int>("ID_Marca")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID_Modelo")
                        .HasName("PK__Modelo__813C23729CB904A5");

                    b.HasIndex(new[] { "ID_Marca" }, "IDX_Carro_Marca");

                    b.ToTable("Modelo", (string)null);
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Modera", b =>
                {
                    b.Property<int>("ID_Admin")
                        .HasColumnType("int");

                    b.Property<int>("ID_Anuncio")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Motivo")
                        .HasColumnType("text");

                    b.HasKey("ID_Admin", "ID_Anuncio", "Data")
                        .HasName("PK__Modera__1F0A2AE08E6661C3");

                    b.HasIndex("ID_Anuncio");

                    b.ToTable("Modera", (string)null);
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.PedidoPromocaoAdmin", b =>
                {
                    b.Property<int>("ID_Pedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Pedido"));

                    b.Property<DateTime>("Data_Pedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("Data_Resposta")
                        .HasColumnType("datetime");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Pendente");

                    b.Property<int?>("ID_Admin_Resposta")
                        .HasColumnType("int");

                    b.Property<int>("ID_Utilizador")
                        .HasColumnType("int");

                    b.Property<string>("Justificacao")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Observacoes_Admin")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Tipo_Utilizador_Atual")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID_Pedido")
                        .HasName("PK__Pedido_P__C5A30BC2");

                    b.HasIndex("ID_Admin_Resposta");

                    b.HasIndex("ID_Utilizador");

                    b.ToTable("PedidoPromocaoAdmin", (string)null);
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Preferencia", b =>
                {
                    b.Property<int>("ID_Utilizador")
                        .HasColumnType("int");

                    b.Property<int>("ID_Marca")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Data_Adicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ID_Utilizador", "ID_Marca")
                        .HasName("PK__Preferen__3BBE60CC9723BEEE");

                    b.HasIndex("ID_Marca");

                    b.ToTable("Preferencias");
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Utilizador", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool?>("Bloqueado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Contacto")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly?>("Data_Bloqueio")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Data_Registo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("Data_Token")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<bool?>("Email_Validado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("ID_Admin_Bloqueio")
                        .HasColumnType("int");

                    b.Property<string>("Morada")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Motivo_Bloqueio")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Ativo");

                    b.Property<string>("Token_Validacao")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID")
                        .HasName("PK__Utilizad__3214EC27EA0E8A85");

                    b.HasIndex("ID_Admin_Bloqueio");

                    b.HasIndex(new[] { "Email" }, "IDX_Usuario_Email");

                    b.HasIndex(new[] { "Status" }, "IDX_Usuario_Status");

                    b.HasIndex(new[] { "Username" }, "UQ__Utilizad__536C85E4E9090F69")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Utilizad__A9D105341B8CEC97")
                        .IsUnique();

                    b.ToTable("Utilizador", (string)null);
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Vendedor", b =>
                {
                    b.Property<int>("ID_Utilizador")
                        .HasColumnType("int");

                    b.Property<string>("Dados_Faturacao")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly?>("Data_Aprovacao")
                        .HasColumnType("date");

                    b.Property<int?>("ID_Aprovacao")
                        .HasColumnType("int");

                    b.Property<string>("NIF")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID_Utilizador")
                        .HasName("PK__Vendedor__020698174C3EBC1E");

                    b.HasIndex("ID_Aprovacao");

                    b.ToTable("Vendedor", (string)null);
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Visita", b =>
                {
                    b.Property<int>("ID_Visita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Visita"));

                    b.Property<DateTime?>("Data_Criacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("Data_Hora")
                        .HasColumnType("datetime");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Pendente");

                    b.Property<int>("ID_Anuncio")
                        .HasColumnType("int");

                    b.Property<int>("ID_Comprador")
                        .HasColumnType("int");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.HasKey("ID_Visita")
                        .HasName("PK__Visita__015899C82633D33D");

                    b.HasIndex("ID_Anuncio");

                    b.HasIndex("ID_Comprador");

                    b.ToTable("Visita");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Admin", b =>
                {
                    b.HasOne("Marketplace_LabWebBD.Models.Utilizador", "ID_UtilizadorNavigation")
                        .WithOne("Admin")
                        .HasForeignKey("Marketplace_LabWebBD.Models.Admin", "ID_Utilizador")
                        .IsRequired()
                        .HasConstraintName("FK__Admin__ID_Utiliz__5441852A");

                    b.Navigation("ID_UtilizadorNavigation");
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Anuncio", b =>
                {
                    b.HasOne("Marketplace_LabWebBD.Models.Carro", "ID_CarroNavigation")
                        .WithMany("Anuncios")
                        .HasForeignKey("ID_Carro")
                        .IsRequired()
                        .HasConstraintName("FK__Anuncio__ID_Carr__7C4F7684");

                    b.HasOne("Marketplace_LabWebBD.Models.Vendedor", "ID_VendedorNavigation")
                        .WithMany("Anuncios")
                        .HasForeignKey("ID_Vendedor")
                        .IsRequired()
                        .HasConstraintName("FK__Anuncio__ID_Vend__7D439ABD");

                    b.HasOne("Marketplace_LabWebBD.Models.Comprador", "Reservado_PorNavigation")
                        .WithMany("Anuncios")
                        .HasForeignKey("Reservado_Por")
                        .HasConstraintName("FK__Anuncio__Reserva__7E37BEF6");

                    b.Navigation("ID_CarroNavigation");

                    b.Navigation("ID_VendedorNavigation");

                    b.Navigation("Reservado_PorNavigation");
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Carro", b =>
                {
                    b.HasOne("Marketplace_LabWebBD.Models.Combustivel", "ID_CombustivelNavigation")
                        .WithMany("Carros")
                        .HasForeignKey("ID_Combustivel")
                        .IsRequired()
                        .HasConstraintName("FK__Carro__ID_Combus__70DDC3D8");

                    b.HasOne("Marketplace_LabWebBD.Models.Modelo", "ID_ModeloNavigation")
                        .WithMany("Carros")
                        .HasForeignKey("ID_Modelo")
                        .IsRequired()
                        .HasConstraintName("FK__Carro__ID_Modelo__6FE99F9F");

                    b.HasOne("Marketplace_LabWebBD.Models.Vendedor", "ID_VendedorNavigation")
                        .WithMany("Carros")
                        .HasForeignKey("ID_Vendedor")
                        .IsRequired()
                        .HasConstraintName("FK__Carro__ID_Vended__71D1E811");

                    b.Navigation("ID_CombustivelNavigation");

                    b.Navigation("ID_ModeloNavigation");

                    b.Navigation("ID_VendedorNavigation");
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Compra", b =>
                {
                    b.HasOne("Marketplace_LabWebBD.Models.Anuncio", "ID_AnuncioNavigation")
                        .WithMany("Compras")
                        .HasForeignKey("ID_Anuncio")
                        .IsRequired()
                        .HasConstraintName("FK__Compra__ID_Anunc__0B91BA14");

                    b.HasOne("Marketplace_LabWebBD.Models.Comprador", "ID_CompradorNavigation")
                        .WithMany("Compras")
                        .HasForeignKey("ID_Comprador")
                        .IsRequired()
                        .HasConstraintName("FK__Compra__ID_Compr__0A9D95DB");

                    b.Navigation("ID_AnuncioNavigation");

                    b.Navigation("ID_CompradorNavigation");
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Comprador", b =>
                {
                    b.HasOne("Marketplace_LabWebBD.Models.Utilizador", "ID_UtilizadorNavigation")
                        .WithMany("Compradors")
                        .HasForeignKey("ID_Utilizador")
                        .IsRequired()
                        .HasConstraintName("FK__Comprador__ID_Ut__59FA5E80");

                    b.Navigation("ID_UtilizadorNavigation");
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Cria", b =>
                {
                    b.HasOne("Marketplace_LabWebBD.Models.Admin", "ID_AdminNavigation")
                        .WithMany("Cria")
                        .HasForeignKey("ID_Admin")
                        .IsRequired()
                        .HasConstraintName("FK__Cria__ID_Admin__14270015");

                    b.HasOne("Marketplace_LabWebBD.Models.Utilizador", "ID_UtilizadorNavigation")
                        .WithMany("Cria")
                        .HasForeignKey("ID_Utilizador")
                        .IsRequired()
                        .HasConstraintName("FK__Cria__ID_Utiliza__151B244E");

                    b.Navigation("ID_AdminNavigation");

                    b.Navigation("ID_UtilizadorNavigation");
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Filtro_Favorito", b =>
                {
                    b.HasOne("Marketplace_LabWebBD.Models.Combustivel", "ID_CombustivelNavigation")
                        .WithMany("Filtro_Favoritos")
                        .HasForeignKey("ID_Combustivel")
                        .HasConstraintName("FK__Filtro_Fa__ID_Co__1BC821DD");

                    b.HasOne("Marketplace_LabWebBD.Models.Comprador", "ID_CompradorNavigation")
                        .WithMany("Filtro_Favoritos")
                        .HasForeignKey("ID_Comprador")
                        .IsRequired()
                        .HasConstraintName("FK__Filtro_Fa__ID_Co__18EBB532");

                    b.HasOne("Marketplace_LabWebBD.Models.Marca", "ID_MarcaNavigation")
                        .WithMany("Filtro_Favoritos")
                        .HasForeignKey("ID_Marca")
                        .HasConstraintName("FK__Filtro_Fa__ID_Ma__19DFD96B");

                    b.HasOne("Marketplace_LabWebBD.Models.Modelo", "ID_ModeloNavigation")
                        .WithMany("Filtro_Favoritos")
                        .HasForeignKey("ID_Modelo")
                        .HasConstraintName("FK__Filtro_Fa__ID_Mo__1AD3FDA4");

                    b.Navigation("ID_CombustivelNavigation");

                    b.Navigation("ID_CompradorNavigation");

                    b.Navigation("ID_MarcaNavigation");

                    b.Navigation("ID_ModeloNavigation");
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Foto", b =>
                {
                    b.HasOne("Marketplace_LabWebBD.Models.Carro", "ID_CarroNavigation")
                        .WithMany("Fotos")
                        .HasForeignKey("ID_Carro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Foto__ID_Carro__75A278F5");

                    b.Navigation("ID_CarroNavigation");
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Historico_Reserva", b =>
                {
                    b.HasOne("Marketplace_LabWebBD.Models.Anuncio", "ID_AnuncioNavigation")
                        .WithMany("Historico_Reservas")
                        .HasForeignKey("ID_Anuncio")
                        .IsRequired()
                        .HasConstraintName("FK__Historico__ID_An__25518C17");

                    b.HasOne("Marketplace_LabWebBD.Models.Comprador", "ID_CompradorNavigation")
                        .WithMany("Historico_Reservas")
                        .HasForeignKey("ID_Comprador")
                        .IsRequired()
                        .HasConstraintName("FK__Historico__ID_Co__2645B050");

                    b.Navigation("ID_AnuncioNavigation");

                    b.Navigation("ID_CompradorNavigation");
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Log_Admin", b =>
                {
                    b.HasOne("Marketplace_LabWebBD.Models.Admin", "ID_AdminNavigation")
                        .WithMany("Log_Admins")
                        .HasForeignKey("ID_Admin")
                        .IsRequired()
                        .HasConstraintName("FK__Log_Admin__ID_Ad__1F98B2C1");

                    b.HasOne("Marketplace_LabWebBD.Models.Anuncio", "ID_Anuncio_AfetadoNavigation")
                        .WithMany("Log_Admins")
                        .HasForeignKey("ID_Anuncio_Afetado")
                        .HasConstraintName("FK__Log_Admin__ID_An__2180FB33");

                    b.HasOne("Marketplace_LabWebBD.Models.Utilizador", "ID_Utilizador_AfetadoNavigation")
                        .WithMany("Log_Admins")
                        .HasForeignKey("ID_Utilizador_Afetado")
                        .HasConstraintName("FK__Log_Admin__ID_Ut__208CD6FA");

                    b.Navigation("ID_AdminNavigation");

                    b.Navigation("ID_Anuncio_AfetadoNavigation");

                    b.Navigation("ID_Utilizador_AfetadoNavigation");
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Modelo", b =>
                {
                    b.HasOne("Marketplace_LabWebBD.Models.Marca", "ID_MarcaNavigation")
                        .WithMany("Modelos")
                        .HasForeignKey("ID_Marca")
                        .IsRequired()
                        .HasConstraintName("FK__Modelo__ID_Marca__693CA210");

                    b.Navigation("ID_MarcaNavigation");
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Modera", b =>
                {
                    b.HasOne("Marketplace_LabWebBD.Models.Admin", "ID_AdminNavigation")
                        .WithMany("Moderas")
                        .HasForeignKey("ID_Admin")
                        .IsRequired()
                        .HasConstraintName("FK__Modera__ID_Admin__0F624AF8");

                    b.HasOne("Marketplace_LabWebBD.Models.Anuncio", "ID_AnuncioNavigation")
                        .WithMany("Moderas")
                        .HasForeignKey("ID_Anuncio")
                        .IsRequired()
                        .HasConstraintName("FK__Modera__ID_Anunc__10566F31");

                    b.Navigation("ID_AdminNavigation");

                    b.Navigation("ID_AnuncioNavigation");
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.PedidoPromocaoAdmin", b =>
                {
                    b.HasOne("Marketplace_LabWebBD.Models.ApplicationUser", "ID_Admin_RespostaNavigation")
                        .WithMany()
                        .HasForeignKey("ID_Admin_Resposta")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Marketplace_LabWebBD.Models.ApplicationUser", "ID_UtilizadorNavigation")
                        .WithMany()
                        .HasForeignKey("ID_Utilizador")
                        .IsRequired();

                    b.Navigation("ID_Admin_RespostaNavigation");

                    b.Navigation("ID_UtilizadorNavigation");
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Preferencia", b =>
                {
                    b.HasOne("Marketplace_LabWebBD.Models.Marca", "ID_MarcaNavigation")
                        .WithMany("Preferencia")
                        .HasForeignKey("ID_Marca")
                        .IsRequired()
                        .HasConstraintName("FK__Preferenc__ID_Ma__66603565");

                    b.HasOne("Marketplace_LabWebBD.Models.Utilizador", "ID_UtilizadorNavigation")
                        .WithMany("Preferencia")
                        .HasForeignKey("ID_Utilizador")
                        .IsRequired()
                        .HasConstraintName("FK__Preferenc__ID_Ut__656C112C");

                    b.Navigation("ID_MarcaNavigation");

                    b.Navigation("ID_UtilizadorNavigation");
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Utilizador", b =>
                {
                    b.HasOne("Marketplace_LabWebBD.Models.Admin", "ID_Admin_BloqueioNavigation")
                        .WithMany("Utilizadors")
                        .HasForeignKey("ID_Admin_Bloqueio")
                        .HasConstraintName("FK__Utilizado__ID_Ad__5535A963");

                    b.Navigation("ID_Admin_BloqueioNavigation");
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Vendedor", b =>
                {
                    b.HasOne("Marketplace_LabWebBD.Models.Admin", "ID_AprovacaoNavigation")
                        .WithMany("Vendedors")
                        .HasForeignKey("ID_Aprovacao")
                        .HasConstraintName("FK__Vendedor__ID_Apr__5EBF139D");

                    b.HasOne("Marketplace_LabWebBD.Models.Utilizador", "ID_UtilizadorNavigation")
                        .WithOne("Vendedor")
                        .HasForeignKey("Marketplace_LabWebBD.Models.Vendedor", "ID_Utilizador")
                        .IsRequired()
                        .HasConstraintName("FK__Vendedor__ID_Uti__5DCAEF64");

                    b.Navigation("ID_AprovacaoNavigation");

                    b.Navigation("ID_UtilizadorNavigation");
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Visita", b =>
                {
                    b.HasOne("Marketplace_LabWebBD.Models.Anuncio", "ID_AnuncioNavigation")
                        .WithMany("Visita")
                        .HasForeignKey("ID_Anuncio")
                        .IsRequired()
                        .HasConstraintName("FK__Visita__ID_Anunc__04E4BC85");

                    b.HasOne("Marketplace_LabWebBD.Models.Comprador", "ID_CompradorNavigation")
                        .WithMany("Visita")
                        .HasForeignKey("ID_Comprador")
                        .IsRequired()
                        .HasConstraintName("FK__Visita__ID_Compr__03F0984C");

                    b.Navigation("ID_AnuncioNavigation");

                    b.Navigation("ID_CompradorNavigation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Marketplace_LabWebBD.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Marketplace_LabWebBD.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Marketplace_LabWebBD.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Marketplace_LabWebBD.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Admin", b =>
                {
                    b.Navigation("Cria");

                    b.Navigation("Log_Admins");

                    b.Navigation("Moderas");

                    b.Navigation("Utilizadors");

                    b.Navigation("Vendedors");
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Anuncio", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("Historico_Reservas");

                    b.Navigation("Log_Admins");

                    b.Navigation("Moderas");

                    b.Navigation("Visita");
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Carro", b =>
                {
                    b.Navigation("Anuncios");

                    b.Navigation("Fotos");
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Combustivel", b =>
                {
                    b.Navigation("Carros");

                    b.Navigation("Filtro_Favoritos");
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Comprador", b =>
                {
                    b.Navigation("Anuncios");

                    b.Navigation("Compras");

                    b.Navigation("Filtro_Favoritos");

                    b.Navigation("Historico_Reservas");

                    b.Navigation("Visita");
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Marca", b =>
                {
                    b.Navigation("Filtro_Favoritos");

                    b.Navigation("Modelos");

                    b.Navigation("Preferencia");
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Modelo", b =>
                {
                    b.Navigation("Carros");

                    b.Navigation("Filtro_Favoritos");
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Utilizador", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Compradors");

                    b.Navigation("Cria");

                    b.Navigation("Log_Admins");

                    b.Navigation("Preferencia");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("Marketplace_LabWebBD.Models.Vendedor", b =>
                {
                    b.Navigation("Anuncios");

                    b.Navigation("Carros");
                });
#pragma warning restore 612, 618
        }
    }
}
